name: riffle
description: A multiplatform music app free, opensource and without ads
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  window_manager: ^0.3.8
  get: ^4.6.6
  audioplayers: ^6.0.0
  audio_service: ^0.18.13
  http: ^1.2.1
  path_provider: ^2.1.3
  path: ^1.9.0
  youtube_explode_dart: ^2.2.1
  get_storage: ^2.1.1
  uuid: ^4.4.0
  super_hot_key: ^0.8.17
  font_awesome_flutter: ^10.7.0
  toastification: ^2.0.0
  url_launcher: ^6.3.0
  system_theme: ^2.3.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^5.1.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7
  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/music_note_24dp_FILL0_wght400_GRAD0_opsz24.png

msix_config:
  display_name: Riffle
  logo_path: assets/msix_logo.png
  capabilities: internetClient