// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPKKZFc17fzlYTlpp06vluEQ00wdrjjU',
    appId: '1:1057023595366:android:6a8e0936876df42160eea7',
    messagingSenderId: '1057023595366',
    projectId: 'riffle-dc901',
    storageBucket: 'riffle-dc901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5FdojFFyEfGSk7uSouxl5AaULzaLcLsA',
    appId: '1:1057023595366:ios:d76b8ea262aa121860eea7',
    messagingSenderId: '1057023595366',
    projectId: 'riffle-dc901',
    storageBucket: 'riffle-dc901.appspot.com',
    iosBundleId: 'com.example.riffle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5FdojFFyEfGSk7uSouxl5AaULzaLcLsA',
    appId: '1:1057023595366:ios:d76b8ea262aa121860eea7',
    messagingSenderId: '1057023595366',
    projectId: 'riffle-dc901',
    storageBucket: 'riffle-dc901.appspot.com',
    iosBundleId: 'com.example.riffle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOVjgA5t0wVDxiwFl7zl6wEeo2UflK98',
    appId: '1:1057023595366:web:a12888e7d9edc80660eea7',
    messagingSenderId: '1057023595366',
    projectId: 'riffle-dc901',
    authDomain: 'riffle-dc901.firebaseapp.com',
    storageBucket: 'riffle-dc901.appspot.com',
    measurementId: 'G-Z3LQ6TNFJH',
  );
}
